run:
  go: "1.22"
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - dist
output:
  sort-results: true
  uniq-by-line: true
linters-settings:
  gofumpt:
    extra-rules: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/DippingCode/easyenv)
    skip-generated: true
  revive:
    severity: warning
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers" ]
      - name: var-naming
      - name: receiver-naming
      - name: package-comments
      - name: if-return
      - name: range-val-address
      - name: early-return
      - name: errorf
      - name: unexported-return
  depguard:
    list-type: denylist
    packages:
      - log
    packages-with-error-message:
      - log: use the repository logging package
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-checks:
      - appendAssign
      - boolExprSimplify
      - dupImport
      - ifElseChain
      - offBy1
      - rangeExprCopy
      - sloppyReassign
      - typeAssertChain
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
linters:
  enable:
    - govet
    - staticcheck
    - gofumpt
    - gci
    - revive
    - gosimple
    - ineffassign
    - typecheck
    - errcheck
    - goconst
    - gocritic
    - misspell
    - gosec
    - nolintlint
  disable:
    - dupl
    - funlen
    - gocyclo
    - wsl
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - gosec
    - linters:
        - gosec
      text: "G115"   # conversões int para string seguras, avalie caso a caso
    - linters:
        - revive
      text: "stutters"
