# Catálogo de ferramentas do EasyEnv
# Campos suportados por item:
# - name, section, type (core|theme|cli|stack), description, homepage
# - brew: { formula: <nome>, cask: <nome> } (opcional)
# - install, uninstall (scripts opcionais, multiline)
# - check_version_cmd, update_cmd
# - deprecated: true|false
# - cleanup: [ ... ]
# - env: [ linhas a injetar no zshrc ]
# - aliases: [ ... ]
# - paths: [ ... ]
# - interactive_config: true|false
# - config_cmd, config_notes

tools:
  # ===== ZSH / CORE =====
  - name: oh-my-zsh
    section: zsh
    type: core
    description: Framework zsh
    homepage: https://ohmyz.sh
    brew: {}
    install: |
      if [ ! -d "$HOME/.oh-my-zsh" ]; then
        RUNZ="$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        CHSH=no RUNZSH=no KEEP_ZSHRC=yes sh -c "$RUNZ" >/dev/null 2>&1 || true
      fi
    uninstall: rm -rf "$HOME/.oh-my-zsh"
    check_version_cmd: 'test -d "$HOME/.oh-my-zsh" && echo "oh-my-zsh installed" || echo "missing"'
    update_cmd: "omz update || true"
    deprecated: false
    cleanup: [ "~/.zcompdump*" ]
    env: []
    aliases: []
    paths: []
    interactive_config: false
    config_cmd: ""
    config_notes: ""
    instaled_version: ""
    latest_version: ""

  - name: powerlevel10k
    section: zsh
    type: theme
    description: Tema rápido e altamente configurável
    homepage: https://github.com/romkatv/powerlevel10k
    brew:
      formula: powerlevel10k
    install: ""
    uninstall: "brew uninstall powerlevel10k || true"
    check_version_cmd: 'p10k version 2>/dev/null || echo "p10k (verifique instalação)"'
    update_cmd: "brew upgrade powerlevel10k || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []
    interactive_config: false
    config_cmd: ""
    config_notes: ""

  # ===== UTILITÁRIOS CLI =====
  - name: yq
    section: cli
    type: cli
    description: Processador YAML
    homepage: https://mikefarah.gitbook.io/yq/
    brew:
      formula: yq
    install: ""
    uninstall: "brew uninstall yq || true"
    check_version_cmd: "yq --version"
    update_cmd: "brew upgrade yq || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: fzf
    section: cli
    type: cli
    description: Fuzzy finder
    homepage: https://github.com/junegunn/fzf
    brew:
      formula: fzf
    install: 'yes | "$(brew --prefix)"/opt/fzf/install >/dev/null || true'
    uninstall: "brew uninstall fzf || true"
    check_version_cmd: "fzf --version | head -n1"
    update_cmd: "brew upgrade fzf || true"
    deprecated: false
    cleanup: [ "~/.fzf*", "~/.cache/fzf" ]
    env:
      - 'if command -v fd >/dev/null 2>&1; then export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"; export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"; elif command -v rg >/dev/null 2>&1; then export FZF_DEFAULT_COMMAND="rg --files --hidden --follow -g !.git"; export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"; fi'
    aliases: []
    paths: []

  - name: zoxide
    section: cli
    type: cli
    description: cd inteligente com ranking
    homepage: https://github.com/ajeetdsouza/zoxide
    brew:
      formula: zoxide
    install: ""
    uninstall: "brew uninstall zoxide || true"
    check_version_cmd: "zoxide --version | head -n1"
    update_cmd: "brew upgrade zoxide || true"
    deprecated: false
    cleanup: []
    env: [ 'eval "$(zoxide init zsh)"' ]
    aliases:
      - 'alias z="zoxide query -l | fzf | xargs -I{} cd \"{}\""' 
    paths: []

  - name: eza
    section: cli
    type: cli
    description: ls moderno
    homepage: https://github.com/eza-community/eza
    brew:
      formula: eza
    install: ""
    uninstall: "brew uninstall eza || true"
    check_version_cmd: "eza --version | head -n1"
    update_cmd: "brew upgrade eza || true"
    deprecated: false
    cleanup: []
    env: []
    aliases:
      - 'alias ls="eza -G"'
      - 'alias ll="eza -la --group-directories-first --icons"'
      - 'alias la="eza -a"'
      - 'alias lt="eza -T"'
    paths: []

  - name: bat
    section: cli
    type: cli
    description: cat com syntax highlight
    homepage: https://github.com/sharkdp/bat
    brew:
      formula: bat
    install: ""
    uninstall: "brew uninstall bat || true"
    check_version_cmd: "bat --version"
    update_cmd: "brew upgrade bat || true"
    deprecated: false
    cleanup: []
    env:
      - "export MANPAGER='sh -c \"col -bx | bat -l man -p\"'"
    aliases: [ 'alias cat="bat -p"' ]
    paths: []

  - name: ripgrep
    section: cli
    type: cli
    description: grep rápido
    homepage: https://github.com/BurntSushi/ripgrep
    brew:
      formula: ripgrep
    install: ""
    uninstall: "brew uninstall ripgrep || true"
    check_version_cmd: "rg --version | head -n1"
    update_cmd: "brew upgrade ripgrep || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias grep="rg"' ]
    paths: []

  - name: fd
    section: cli
    type: cli
    description: find simplificado
    homepage: https://github.com/sharkdp/fd
    brew:
      formula: fd
    install: ""
    uninstall: "brew uninstall fd || true"
    check_version_cmd: "fd --version | head -n1"
    update_cmd: "brew upgrade fd || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: direnv
    section: cli
    type: cli
    description: variáveis por diretório
    homepage: https://direnv.net
    brew:
      formula: direnv
    install: ""
    uninstall: "brew uninstall direnv || true"
    check_version_cmd: "direnv --version"
    update_cmd: "brew upgrade direnv || true"
    deprecated: false
    cleanup: []
    env: [ 'eval "$(direnv hook zsh)"' ]
    aliases: []
    paths: []

  - name: thefuck
    section: cli
    type: cli
    description: corrige comandos errados
    homepage: https://github.com/nvbn/thefuck
    brew:
      formula: thefuck
    install: ""
    uninstall: "brew uninstall thefuck || true"
    check_version_cmd: "thefuck --version | head -n1"
    update_cmd: "brew upgrade thefuck || true"
    deprecated: false
    cleanup: []
    env: [ 'eval "$(thefuck --alias)"' ]
    aliases: []
    paths: []

  - name: httpie
    section: cli
    type: cli
    description: cliente HTTP amigável
    homepage: https://httpie.io
    brew:
      formula: httpie
    install: ""
    uninstall: "brew uninstall httpie || true"
    check_version_cmd: "http --version | head -n1"
    update_cmd: "brew upgrade httpie || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias http="httpie"' ]
    paths: []

  - name: jq
    section: cli
    type: cli
    description: processador JSON
    homepage: https://jqlang.github.io/jq/
    brew:
      formula: jq
    install: ""
    uninstall: "brew uninstall jq || true"
    check_version_cmd: "jq --version"
    update_cmd: "brew upgrade jq || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias jqc="jq -C . | less -R"' ]
    paths: []

  - name: gh
    section: cli
    type: cli
    description: GitHub CLI
    homepage: https://cli.github.com
    brew:
      formula: gh
    install: ""
    uninstall: "brew uninstall gh || true"
    check_version_cmd: "gh --version | head -n1"
    update_cmd: "brew upgrade gh || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias ghl="gh auth login"' ]
    paths: []

  - name: ghq
    section: cli
    type: cli
    description: organizar repositórios git
    homepage: https://github.com/x-motemen/ghq
    brew:
      formula: ghq
    install: ""
    uninstall: "brew uninstall ghq || true"
    check_version_cmd: "ghq --version | head -n1"
    update_cmd: "brew upgrade ghq || true"
    deprecated: false
    cleanup: []
    env: []
    aliases:
      - |
        alias ghqget="gh repo list --limit 100 | fzf | awk '{print \$1}' | xargs -I{} ghq get {}"
    paths: []

  - name: asciinema
    section: cli
    type: cli
    description: gravar sessões de terminal
    homepage: https://asciinema.org
    brew:
      formula: asciinema
    install: ""
    uninstall: "brew uninstall asciinema || true"
    check_version_cmd: "asciinema --version"
    update_cmd: "brew upgrade asciinema || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: htop
    section: cli
    type: cli
    description: monitor de processos
    homepage: https://htop.dev
    brew:
      formula: htop
    install: ""
    uninstall: "brew uninstall htop || true"
    check_version_cmd: "htop --version | head -n1"
    update_cmd: "brew upgrade htop || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: btop
    section: cli
    type: cli
    description: monitor bonito
    homepage: https://github.com/aristocratos/btop
    brew:
      formula: btop
    install: ""
    uninstall: "brew uninstall btop || true"
    check_version_cmd: "btop --version | head -n1"
    update_cmd: "brew upgrade btop || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias top="btop"' ]
    paths: []

  - name: mtr
    section: cli
    type: cli
    description: ping + traceroute
    homepage: https://www.bitwizard.nl/mtr/
    brew:
      formula: mtr
    install: ""
    uninstall: "brew uninstall mtr || true"
    check_version_cmd: "mtr --version | head -n1"
    update_cmd: "brew upgrade mtr || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias nettr="sudo mtr -c 50 1.1.1.1"' ]
    paths: []

  - name: iperf3
    section: cli
    type: cli
    description: throughput de rede
    homepage: https://software.es.net/iperf/
    brew:
      formula: iperf3
    install: ""
    uninstall: "brew uninstall iperf3 || true"
    check_version_cmd: "iperf3 --version | head -n1"
    update_cmd: "brew upgrade iperf3 || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: glances
    section: cli
    type: cli
    description: monitor multiplataforma
    homepage: https://nicolargo.github.io/glances/
    brew:
      formula: glances
    install: ""
    uninstall: "brew uninstall glances || true"
    check_version_cmd: "glances --version | head -n1"
    update_cmd: "brew upgrade glances || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias gl="glances"' ]
    paths: []

  - name: fastfetch
    section: cli
    type: cli
    description: resumo do sistema (moderno)
    homepage: https://github.com/fastfetch-cli/fastfetch
    brew:
      formula: fastfetch
    install: ""
    uninstall: "brew uninstall fastfetch || true"
    check_version_cmd: "fastfetch --version | head -n1"
    update_cmd: "brew upgrade fastfetch || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: [ 'alias fetch="fastfetch || neofetch"' ]
    paths: []

  - name: neofetch
    section: cli
    type: cli
    description: resumo do sistema (clássico)
    homepage: https://github.com/dylanaraps/neofetch
    brew:
      formula: neofetch
    install: ""
    uninstall: "brew uninstall neofetch || true"
    check_version_cmd: "neofetch --version 2>/dev/null || echo neofetch"
    update_cmd: "brew upgrade neofetch || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: starship
    section: zsh
    type: theme
    description: prompt universal
    homepage: https://starship.rs
    brew:
      formula: starship
    install: ""
    uninstall: "brew uninstall starship || true"
    check_version_cmd: "starship --version | head -n1"
    update_cmd: "brew upgrade starship || true"
    deprecated: false
    cleanup: []
    env: [ '# eval "$(starship init zsh)"' ]
    aliases: []
    paths: []

  - name: zsh-autosuggestions
    section: zsh
    type: cli
    description: sugestões no zsh
    homepage: https://github.com/zsh-users/zsh-autosuggestions
    brew:
      formula: zsh-autosuggestions
    install: ""
    uninstall: "brew uninstall zsh-autosuggestions || true"
    check_version_cmd: "zsh -ic 'echo $ZSH_VERSION && echo autosuggestions-ok'"
    update_cmd: "brew upgrade zsh-autosuggestions || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: zsh-syntax-highlighting
    section: zsh
    type: cli
    description: highlight de sintaxe
    homepage: https://github.com/zsh-users/zsh-syntax-highlighting
    brew:
      formula: zsh-syntax-highlighting
    install: ""
    uninstall: "brew uninstall zsh-syntax-highlighting || true"
    check_version_cmd: "zsh -ic 'echo $ZSH_VERSION && echo syntax-ok'"
    update_cmd: "brew upgrade zsh-syntax-highlighting || true"
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []

  - name: fzf-tab
    section: zsh
    type: cli
    description: autocomplete via fzf
    homepage: https://github.com/Aloxaf/fzf-tab
    brew: {}
    install: |
      mkdir -p "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"
      [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab" ] || \
        git clone https://github.com/Aloxaf/fzf-tab "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab"
    uninstall: |
      rm -rf "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab"
    check_version_cmd: 'test -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab" && echo fzf-tab'
    update_cmd: 'git -C "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab" pull || true'
    deprecated: false
    cleanup: []
    env: []
    aliases: []
    paths: []